package com.pokedex

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.myapplication.R
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn

class MainViewModel : ViewModel() {

    val pokemonMap = listOf(
        "bulbasaur" to R.drawable.bulbasaur_1,
        "ivysaur" to R.drawable.ivysaur_2,
        "venusaur" to R.drawable.venusaur_3,
        "charmander" to R.drawable.charmander_4,
        "charmeleon" to R.drawable.charmeleon_5,
        "charizard" to R.drawable.charizard_6,
        "squirtle" to R.drawable.squirtle_7,
        "wartortle" to R.drawable.wartortle_8,
        "blastoise" to R.drawable.blastoise_9,
        "caterpie" to R.drawable.caterpie_10,
        "metapod" to R.drawable.metapod_11,
        "butterfree" to R.drawable.butterfree_12,
        "weedle" to R.drawable.weedle_13,
        "kakuna" to R.drawable.kakuna_14,
        "beedrill" to R.drawable.beedrill_15,
        "pidgey" to R.drawable.pidgey_16,
        "pidgeotto" to R.drawable.pidgeotto_17,
        "pidgeot" to R.drawable.pidgeot_18,
        "rattata" to R.drawable.rattata_19,
        "raticate" to R.drawable.raticate_20,
        "spearow" to R.drawable.spearow_21,
        "fearow" to R.drawable.fearow_22,
        "ekans" to R.drawable.ekans_23,
        "arbok" to R.drawable.arbok_24,
        "pikachu" to R.drawable.pikachu_25,
        "raichu" to R.drawable.raichu_26,
        "sandshrew" to R.drawable.sandshrew_27,
        "sandslash" to R.drawable.sandslash_28,
        "nidoran♀" to R.drawable.nidoran_29,
        "nidorina" to R.drawable.nidorina_30,
        "nidoqueen" to R.drawable.nidoqueen_31,
        "nidoran♂" to R.drawable.nidoran_32,
        "nidorino" to R.drawable.nidorino_33,
        "nidoking" to R.drawable.nidoking_34,
        "clefairy" to R.drawable.clefairy_35,
        "clefable" to R.drawable.clefable_36,
        "vulpix" to R.drawable.vulpix_37,
        "ninetales" to R.drawable.ninetales_38,
        "jigglypuff" to R.drawable.jigglypuff_39,
        "wigglytuff" to R.drawable.wigglytuff_40,
        "zubat" to R.drawable.zubat_41,
        "golbat" to R.drawable.golbat_42,
        "oddish" to R.drawable.oddish_43,
        "gloom" to R.drawable.gloom_44,
        "vileplume" to R.drawable.vileplume_45,
        "paras" to R.drawable.paras_46,
        "parasect" to R.drawable.parasect_47,
        "venonat" to R.drawable.venonat_48,
        "venomoth" to R.drawable.venomoth_49,
        "diglett" to R.drawable.diglett_50,
        "dugtrio" to R.drawable.dugtrio_51,
        "meowth" to R.drawable.meowth_52,
        "persian" to R.drawable.persian_53,
        "psyduck" to R.drawable.psyduck_54,
        "golduck" to R.drawable.golduck_55,
        "mankey" to R.drawable.mankey_56,
        "primeape" to R.drawable.primeape_57,
        "growlithe" to R.drawable.growlithe_58,
        "arcanine" to R.drawable.arcanine_59,
        "poliwag" to R.drawable.poliwag_60,
        "poliwhirl" to R.drawable.poliwhirl_61,
        "poliwrath" to R.drawable.poliwrath_62,
        "abra" to R.drawable.abra_63,
        "kadabra" to R.drawable.kadabra_64,
        "alakazam" to R.drawable.alakazam_65,
        "machop" to R.drawable.machop_66,
        "machoke" to R.drawable.machoke_67,
        "machamp" to R.drawable.machamp_68,
        "bellsprout" to R.drawable.bellsprout_69,
        "weepinbell" to R.drawable.weepinbell_70,
        "victreebel" to R.drawable.victreebel_71,
        "tentacool" to R.drawable.tentacool_72,
        "tentacruel" to R.drawable.tentacruel_73,
        "geodude" to R.drawable.geodude_74,
        "graveler" to R.drawable.graveler_75,
        "golem" to R.drawable.golem_76,
        "ponyta" to R.drawable.ponyta_77,
        "rapidash" to R.drawable.rapidash_78,
        "slowpoke" to R.drawable.slowpoke_79,
        "slowbro" to R.drawable.slowbro_80,
        "magnemite" to R.drawable.magnemite_81,
        "magneton" to R.drawable.magneton_82,
        "farfetch'd" to R.drawable.farfetch_d_83,
        "doduo" to R.drawable.doduo_84,
        "dodrio" to R.drawable.dodrio_85,
        "seel" to R.drawable.seel_86,
        "dewgong" to R.drawable.dewgong_87,
        "grimer" to R.drawable.grimer_88,
        "muk" to R.drawable.muk_89,
        "shellder" to R.drawable.shellder_90,
        "cloyster" to R.drawable.cloyster_91,
        "gastly" to R.drawable.gastly_92,
        "haunter" to R.drawable.haunter_93,
        "gengar" to R.drawable.gengar_94,
        "onix" to R.drawable.onix_95,
        "drowzee" to R.drawable.drowzee_96,
        "hypno" to R.drawable.hypno_97,
        "krabby" to R.drawable.krabby_98,
        "kingler" to R.drawable.kingler_99,
        "voltorb" to R.drawable.voltorb_100,
        "electrode" to R.drawable.electrode_101,
        "exeggcute" to R.drawable.exeggcute_102,
        "exeggutor" to R.drawable.exeggutor_103,
        "cubone" to R.drawable.cubone_104,
        "marowak" to R.drawable.marowak_105,
        "hitmonlee" to R.drawable.hitmonlee_106,
        "hitmonchan" to R.drawable.hitmonchan_107,
        "lickitung" to R.drawable.lickitung_108,
        "koffing" to R.drawable.koffing_109,
        "weezing" to R.drawable.weezing_110,
        "rhyhorn" to R.drawable.rhyhorn_111,
        "rhydon" to R.drawable.rhydon_112,
        "chansey" to R.drawable.chansey_113,
        "tangela" to R.drawable.tangela_114,
        "kangaskhan" to R.drawable.kangaskhan_115,
        "horsea" to R.drawable.horsea_116,
        "seadra" to R.drawable.seadra_117,
        "goldeen" to R.drawable.goldeen_118,
        "seaking" to R.drawable.seaking_119,
        "staryu" to R.drawable.staryu_120,
        "starmie" to R.drawable.starmie_121,
        "mr. mime" to R.drawable.mr__mime_122,
        "scyther" to R.drawable.scyther_123,
        "jynx" to R.drawable.jynx_124,
        "electabuzz" to R.drawable.electabuzz_125,
        "magmar" to R.drawable.magmar_126,
        "pinsir" to R.drawable.pinsir_127,
        "tauros" to R.drawable.tauros_128,
        "magikarp" to R.drawable.magikarp_129,
        "gyarados" to R.drawable.gyarados_130,
        "lapras" to R.drawable.lapras_131,
        "ditto" to R.drawable.ditto_132,
        "eevee" to R.drawable.eevee_133,
        "vaporeon" to R.drawable.vaporeon_134,
        "jolteon" to R.drawable.jolteon_135,
        "flareon" to R.drawable.flareon_136,
        "porygon" to R.drawable.porygon_137,
        "omanyte" to R.drawable.omanyte_138,
        "omastar" to R.drawable.omastar_139,
        "kabuto" to R.drawable.kabuto_140,
        "kabutops" to R.drawable.kabutops_141,
        "aerodactyl" to R.drawable.aerodactyl_142,
        "snorlax" to R.drawable.snorlax_143,
        "articuno" to R.drawable.articuno_144,
        "zapdos" to R.drawable.zapdos_145,
        "moltres" to R.drawable.moltres_146,
        "dratini" to R.drawable.dratini_147,
        "dragonair" to R.drawable.dragonair_148,
        "dragonite" to R.drawable.dragonite_149,
        "mewtwo" to R.drawable.mewtwo_150,
        "mew" to R.drawable.mew_151
    )

    // first state whether the search is happening or not
    private val _isSearching = MutableStateFlow(false)
    val isSearching = _isSearching.asStateFlow()

    // third state the list to be filtered
    private val _pokemonList = MutableStateFlow(pokemonMap)
    val pokemonList = _pokemonList.asStateFlow()

    fun onSearchTextChange(text: String) {
        _pokemonList.value = pokemonMap.filter { poke ->
            poke.first.contains(text.trim(), true)
        }
    }

}

